package com.qvety.practice;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.EnumType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.sql.Types;
import java.time.OffsetDateTime;
import java.util.UUID;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.JdbcType;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.dialect.type.PostgreSQLEnumJdbcType;

/**
 * Platform table: no practice_id. The id is generated by Postgres (uuidv7()) and read back on insert.
 * DynamicUpdate: qvety_app may update identity columns only (column grant in V3); a full-row UPDATE
 * would touch status and be refused. Country, currency, locale, timezone, status, trial end are
 * super-admin fields and never written from here.
 */
@Entity
@Table(name = "practices")
@DynamicUpdate
@Getter
@Setter
@NoArgsConstructor
public class Practice {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)   // Postgres default uuidv7(), read back via RETURNING
    @Column(name = "id", insertable = false, updatable = false)
    private UUID id;

    @Column(name = "name", nullable = false)
    private String name;

    @JdbcTypeCode(Types.CHAR)   // Postgres char(n) is bpchar; validate needs the JDBC CHAR type, not VARCHAR
    @Column(name = "country", nullable = false, updatable = false, length = 2)
    private String country;

    @JdbcTypeCode(Types.CHAR)
    @Column(name = "currency", nullable = false, updatable = false, length = 3)
    private String currency;

    @Column(name = "locale", nullable = false, updatable = false)
    private String locale;

    @Column(name = "timezone", nullable = false, updatable = false)
    private String timezone;

    @Enumerated(EnumType.STRING)
    @JdbcType(PostgreSQLEnumJdbcType.class)
    @Column(name = "status", nullable = false, updatable = false, columnDefinition = "practice_status")
    private PracticeStatus status;

    @Column(name = "address")
    private String address;

    @Column(name = "phone")
    private String phone;

    @Column(name = "vat_number")
    private String vatNumber;

    @Column(name = "tax_rate_percent", nullable = false, precision = 5, scale = 2)
    private BigDecimal taxRatePercent;

    @Column(name = "trial_ends_at", updatable = false)
    private OffsetDateTime trialEndsAt;

    /** Set by the platform when a practice is closed; retention is counted from here (part 11). */
    @Column(name = "closed_at", updatable = false)
    private OffsetDateTime closedAt;

    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime updatedAt;
}
