export * from './appointments.service';
import { AppointmentsApi } from './appointments.service';
export * from './audit.service';
import { AuditApi } from './audit.service';
export * from './auth.service';
import { AuthApi } from './auth.service';
export * from './clients.service';
import { ClientsApi } from './clients.service';
export * from './me.service';
import { MeApi } from './me.service';
export * from './patients.service';
import { PatientsApi } from './patients.service';
export * from './platform.service';
import { PlatformApi } from './platform.service';
export * from './practice.service';
import { PracticeApi } from './practice.service';
export * from './reference.service';
import { ReferenceApi } from './reference.service';
export * from './schedule.service';
import { ScheduleApi } from './schedule.service';
export * from './users.service';
import { UsersApi } from './users.service';
export const APIS = [AppointmentsApi, AuditApi, AuthApi, ClientsApi, MeApi, PatientsApi, PlatformApi, PracticeApi, ReferenceApi, ScheduleApi, UsersApi];
