export * from './audit.service';
import { AuditApi } from './audit.service';
export * from './auth.service';
import { AuthApi } from './auth.service';
export * from './clients.service';
import { ClientsApi } from './clients.service';
export * from './me.service';
import { MeApi } from './me.service';
export * from './patients.service';
import { PatientsApi } from './patients.service';
export * from './practice.service';
import { PracticeApi } from './practice.service';
export * from './users.service';
import { UsersApi } from './users.service';
export const APIS = [AuditApi, AuthApi, ClientsApi, MeApi, PatientsApi, PracticeApi, UsersApi];
