/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AllergyRequestDto { 
    substance: string;
    reaction?: string;
    severity: AllergyRequestDto.SeverityEnum;
}
export namespace AllergyRequestDto {
    export const SeverityEnum = {
        Mild: 'mild',
        Moderate: 'moderate',
        Severe: 'severe'
    } as const;
    export type SeverityEnum = typeof SeverityEnum[keyof typeof SeverityEnum];
}


