/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppointmentRequestDto { 
    patientId: string;
    veterinarianId: string;
    roomId: string;
    appointmentTypeId: string;
    start: string;
    durationMinutes: number;
    reason?: string;
    notes?: string;
    /**
     * Create the row already checked in, with origin walk_in. Ignored on update.
     */
    walkIn?: boolean;
}

