/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppointmentDto { 
    id: string;
    patientId: string;
    patientName: string;
    clientId: string;
    clientName: string;
    veterinarianId: string;
    veterinarianName: string;
    roomId: string;
    roomName: string;
    appointmentTypeId: string;
    appointmentTypeName: string;
    color?: string;
    startsAt: string;
    endsAt: string;
    status: AppointmentDto.StatusEnum;
    origin: AppointmentDto.OriginEnum;
    checkedInAt?: string;
    reason?: string;
    notes?: string;
    version: number;
}
export namespace AppointmentDto {
    export const StatusEnum = {
        Scheduled: 'scheduled',
        CheckedIn: 'checked_in',
        InProgress: 'in_progress',
        Completed: 'completed',
        Cancelled: 'cancelled',
        NoShow: 'no_show'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const OriginEnum = {
        Scheduled: 'scheduled',
        WalkIn: 'walk_in'
    } as const;
    export type OriginEnum = typeof OriginEnum[keyof typeof OriginEnum];
}


