/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppointmentTypeDto { 
    id: string;
    name: string;
    durationMinutes: number;
    color?: string;
    active: boolean;
    version: number;
    createdAt: string;
    updatedAt: string;
}

