/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuditEntryDto { 
    id: string;
    userId?: string;
    tableName: string;
    rowId: string;
    action: AuditEntryDto.ActionEnum;
    before?: { [key: string]: any; };
    after?: { [key: string]: any; };
    at: string;
}
export namespace AuditEntryDto {
    export const ActionEnum = {
        Insert: 'insert',
        Update: 'update',
        Delete: 'delete'
    } as const;
    export type ActionEnum = typeof ActionEnum[keyof typeof ActionEnum];
}


