/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BoardEntryDto } from './boardEntry';


export interface BoardDto { 
    waiting: Array<BoardEntryDto>;
    inExam: Array<BoardEntryDto>;
    done: Array<BoardEntryDto>;
}

