/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BoardEntryDto { 
    id: string;
    patientName: string;
    clientName: string;
    veterinarianName: string;
    roomName: string;
    startsAt: string;
    status: BoardEntryDto.StatusEnum;
    origin: BoardEntryDto.OriginEnum;
    minutesWaiting?: number;
    reason?: string;
}
export namespace BoardEntryDto {
    export const StatusEnum = {
        Scheduled: 'scheduled',
        CheckedIn: 'checked_in',
        InProgress: 'in_progress',
        Completed: 'completed',
        Cancelled: 'cancelled',
        NoShow: 'no_show'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const OriginEnum = {
        Scheduled: 'scheduled',
        WalkIn: 'walk_in'
    } as const;
    export type OriginEnum = typeof OriginEnum[keyof typeof OriginEnum];
}


