/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChangeStatusRequestDto { 
    status: ChangeStatusRequestDto.StatusEnum;
    reason: string;
}
export namespace ChangeStatusRequestDto {
    export const StatusEnum = {
        Trial: 'trial',
        Active: 'active',
        PastDue: 'past_due',
        Suspended: 'suspended',
        Closed: 'closed'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


