/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientRequestDto { 
    fullName: string;
    preferredName?: string;
    phone?: string;
    phoneSecondary?: string;
    email?: string;
    address?: string;
    notes?: string;
    preferredLocale?: string;
}

