/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatePracticeRequestDto { 
    name: string;
    country: string;
    currency: string;
    locale: string;
    timezone: string;
    adminName: string;
    adminPhone: string;
    adminEmail?: string;
    /**
     * Whether the first admin is also a veterinarian; most clinic owners are.
     */
    adminVeterinarian?: boolean;
}

