/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DayColumnDto } from './dayColumn';


export interface DayDto { 
    date: string;
    /**
     * IANA zone of the practice; the client renders every instant in it
     */
    timezone: string;
    opens?: string;
    closes?: string;
    columns: Array<DayColumnDto>;
}

