/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppointmentDto } from './appointment';


export interface DayColumnDto { 
    veterinarianId: string;
    veterinarianName: string;
    appointments: Array<AppointmentDto>;
}

