/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadataDto } from './pageMetadata';
import { ClientDto } from './client';


export interface PagedModelClientDto { 
    content?: Array<ClientDto>;
    page?: PageMetadataDto;
}

