/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortObjectDto } from './sortObject';


export interface PageableObjectDto { 
    offset?: number;
    paged?: boolean;
    pageNumber?: number;
    pageSize?: number;
    sort?: SortObjectDto;
    unpaged?: boolean;
}

