/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditEntryDto } from './auditEntry';
import { PageMetadataDto } from './pageMetadata';


export interface PagedModelAuditEntryDto { 
    content?: Array<AuditEntryDto>;
    page?: PageMetadataDto;
}

