/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatientWeightDto { 
    id: string;
    patientId: string;
    measuredAt: string;
    weightKg: number;
    voidedAt?: string;
    voidReason?: string;
    createdAt: string;
}

