/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatientAllergyDto { 
    id: string;
    patientId: string;
    substance: string;
    reaction?: string;
    severity: PatientAllergyDto.SeverityEnum;
    notedBy: string;
    retractedAt?: string;
    retractedReason?: string;
    createdAt: string;
}
export namespace PatientAllergyDto {
    export const SeverityEnum = {
        Mild: 'mild',
        Moderate: 'moderate',
        Severe: 'severe'
    } as const;
    export type SeverityEnum = typeof SeverityEnum[keyof typeof SeverityEnum];
}


