/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PatientWeightDto } from './patientWeight';
import { PatientAllergyDto } from './patientAllergy';
import { PatientDto } from './patient';


export interface PatientDetailDto { 
    patient: PatientDto;
    latestWeight?: PatientWeightDto;
    activeAllergies: Array<PatientAllergyDto>;
}

