/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatientRequestDto { 
    clientId: string;
    name: string;
    species: PatientRequestDto.SpeciesEnum;
    breed?: string;
    sex?: PatientRequestDto.SexEnum;
    dateOfBirth?: string;
    ageApproximate?: string;
    color?: string;
    microchip?: string;
    notes?: string;
}
export namespace PatientRequestDto {
    export const SpeciesEnum = {
        Dog: 'dog',
        Cat: 'cat',
        Bird: 'bird',
        Rabbit: 'rabbit',
        Rodent: 'rodent',
        Reptile: 'reptile',
        Horse: 'horse',
        Livestock: 'livestock',
        Other: 'other'
    } as const;
    export type SpeciesEnum = typeof SpeciesEnum[keyof typeof SpeciesEnum];
    export const SexEnum = {
        Male: 'male',
        Female: 'female',
        MaleNeutered: 'male_neutered',
        FemaleSpayed: 'female_spayed',
        Unknown: 'unknown'
    } as const;
    export type SexEnum = typeof SexEnum[keyof typeof SexEnum];
}


