/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PracticeSummaryDto { 
    id: string;
    name: string;
    country: string;
    currency: string;
    status: PracticeSummaryDto.StatusEnum;
    trialEndsAt?: string;
    closedAt?: string;
    createdAt: string;
}
export namespace PracticeSummaryDto {
    export const StatusEnum = {
        Trial: 'trial',
        Active: 'active',
        PastDue: 'past_due',
        Suspended: 'suspended',
        Closed: 'closed'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


