/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PracticeDto { 
    id?: string;
    name?: string;
    country?: string;
    currency?: string;
    locale?: string;
    timezone?: string;
    status?: PracticeDtoStatusEnum;
    address?: string;
    phone?: string;
    vatNumber?: string;
    taxRatePercent?: number;
    trialEndsAt?: string;
}
export enum PracticeDtoStatusEnum {
    Trial = 'trial',
    Active = 'active',
    PastDue = 'past_due',
    Suspended = 'suspended',
    Closed = 'closed'
};



