/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PracticeUpdateRequestDto { 
    name: string;
    address?: string;
    phone?: string;
    vatNumber?: string;
    taxRatePercent: number;
}

