/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PracticeSummaryDto } from './practiceSummary';


export interface PracticeCreatedDto { 
    practice: PracticeSummaryDto;
    /**
     * The admin\'s login identifier, normalized to E.164
     */
    adminPhone: string;
    /**
     * Shown once; not stored in readable form
     */
    temporaryPassword: string;
}

