/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServiceDto { 
    id: string;
    name: string;
    price: number;
    /**
     * Practice currency; set by the server, never sent
     */
    currency: string;
    active: boolean;
    version: number;
    createdAt: string;
    updatedAt: string;
}

