/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StatusChangeRequestDto { 
    status: StatusChangeRequestDto.StatusEnum;
}
export namespace StatusChangeRequestDto {
    export const StatusEnum = {
        Scheduled: 'scheduled',
        CheckedIn: 'checked_in',
        InProgress: 'in_progress',
        Completed: 'completed',
        Cancelled: 'cancelled',
        NoShow: 'no_show'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


