/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserUpdateRequestDto { 
    fullName: string;
    role: UserUpdateRequestDto.RoleEnum;
    veterinarian?: boolean;
    licenseNumber?: string;
    phone?: string;
}
export namespace UserUpdateRequestDto {
    export const RoleEnum = {
        Admin: 'admin',
        Veterinarian: 'veterinarian',
        Technician: 'technician',
        FrontDesk: 'front_desk'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


